window.CattaAddonDB = window.CattaAddonDB || {};
window.CattaAddonDB["SOL_V12"] = [
    { dummyTag: "<!-- [CATTA_SYNC:GEMINI_ROMANCE18] -->", fileKey: "sol_01_12", promptId: "01_12SOLEpic" },
    { dummyTag: "<!-- [CATTA_SYNC:SLOW_BURN] -->", fileKey: "sol_02", promptId: "02_STORY_PACING_ENGINE" },
    { dummyTag: "<!-- [CATTA_SYNC:BOSSY_USER] -->", fileKey: "sol_03", promptId: "03_CONSENT_GATEWAY" },
    { dummyTag: "<!-- [CATTA_SYNC:TEASING_NPC] -->", fileKey: "sol_04", promptId: "04_TENSION_BUILDER" },
    { dummyTag: "<!-- [CATTA_SYNC:LANG_THAI] -->", fileKey: "sol_05", promptId: "05_OUTPUT_LANGUAGE_PROTOCOL" },
    { dummyTag: "<!--[CATTA_SYNC:FLAG_GREEN] -->", fileKey: "sol_07", promptId: "07_GREEN_FLAG" },
    { dummyTag: "<!-- [CATTA_SYNC:FLAG_RED] -->", fileKey: "sol_08", promptId: "08_RED_FLAG" },
    { dummyTag: "<!-- [CATTA_SYNC:FLAG_BLACK] -->", fileKey: "sol_09", promptId: "09_BLACK_FLAG" },
    { dummyTag: "<!--[CATTA_SYNC:TIMING] -->", fileKey: "sol_10", promptId: "10_TEMPORAL_ANCHOR" },
    { dummyTag: "<!--[CATTA_SYNC:ANTI_TELEPATHY] -->", fileKey: "sol_11", promptId: "11_ANTI_TELEPATHY" },
    { dummyTag: "<!-- [CATTA_SYNC:NPC_BEHAVIOR] -->", fileKey: "sol_12", promptId: "12_NPC_SIMULATION" },
    { dummyTag: "<!-- [CATTA_SYNC:ALIGNMENT_SYNC] -->", fileKey: "sol_13_1", promptId: "13_1_DYNAMIC_CONSENT_ENGINE" },
    { dummyTag: "<!-- [CATTA_SYNC:DYNAMIC_NPC] -->", fileKey: "sol_13", promptId: "13_SCENE_RENDERER" },
    { dummyTag: "<!--[CATTA_SYNC:THIRD_PERSON] -->", fileKey: "sol_15", promptId: "15_NARRATION_STYLE" },
    { dummyTag: "<!--[CATTA_SYNC:WRITING_STYLE] -->", fileKey: "sol_16", promptId: "16_CHAMELEON_LENS_CORE" },
    { dummyTag: "<!--[CATTA_SYNC:LORE_KEEPER] -->", fileKey: "sol_17", promptId: "17_REALITY_ANCHOR" },
    { dummyTag: "<!-- [CATTA_SYNC:OBSERVABLE_ONLY] -->", fileKey: "sol_19", promptId: "19_ABSOLUTE_ANTI-GODMODE" },
    { dummyTag: "<!--[CATTA_SYNC:THAI_NOVEL_STANDARD] -->", fileKey: "sol_20", promptId: "20_THAI_SYNTAX" },
    { dummyTag: "<!-- [CATTA_SYNC:CONTINUITY] -->", fileKey: "sol_21", promptId: "21_LLM_TROPES_BAN & CONTINUITY" },
    { dummyTag: "<!--[CATTA_SYNC:DESC_MODE_L] -->", fileKey: "sol_22", promptId: "22_MODE_L" },
    { dummyTag: "<!-- [CATTA_SYNC:DESC_MODE_M] -->", fileKey: "sol_23", promptId: "23_MODE_M" },
    { dummyTag: "<!-- [CATTA_SYNC:DESC_MODE_S] -->", fileKey: "sol_24", promptId: "24_MODE_S" },
    { dummyTag: "<!--[CATTA_SYNC:OBSESSIVE_MADNESS] -->", fileKey: "sol_25", promptId: "25_OBSESSIVE_MADNESS" },
    { dummyTag: "<!--[CATTA_SYNC:GOTHIC_BY_MORS] -->", fileKey: "sol_26", promptId: "26_court-gothicVtMbyMors" },
    { dummyTag: "<!-- [CATTA_SYNC:GOTHIC_DECADENCE] -->", fileKey: "sol_27", promptId: "27_GOTHIC-DECADENCE" },
    { dummyTag: "<!-- [CATTA_SYNC:SENSUAL_FEVER] -->", fileKey: "sol_28", promptId: "28_SENSUAL-FEVER" },
    { dummyTag: "<!-- [CATTA_SYNC:GRITTY_SURVIVAL] -->", fileKey: "sol_29", promptId: "29_GRITTY-SURVIVAL" },
    { dummyTag: "<!-- [CATTA_SYNC:ETERNAL_CULTIVATION] -->", fileKey: "sol_30", promptId: "30_ETERNAL-CULTIVATION" },
    { dummyTag: "<!-- [CATTA_SYNC:COZY_NOSTALGIA] -->", fileKey: "sol_31", promptId: "31_COZY-NOSTALGIA" },
    { dummyTag: "<!-- [CATTA_SYNC:NEON_DYSTOPIA] -->", fileKey: "sol_32", promptId: "32_NEON-DYSTOPIA" },
    { dummyTag: "<!-- [CATTA_SYNC:NOIR_SYNDICATE] -->", fileKey: "sol_33", promptId: "33_NOIR-SYNDICATE" },
    { dummyTag: "<!-- [CATTA_SYNC:WEB_NOVEL] -->", fileKey: "sol_34", promptId: "34_Web-novel" },
    { dummyTag: "<!--[CATTA_SYNC:FANTASY_WUXIA] -->", fileKey: "sol_35", promptId: "35_FantasyWuxia" },
    { dummyTag: "<!--[CATTA_SYNC:VICTORIAN_ELEGANCE] -->", fileKey: "sol_36", promptId: "36_VICTORIAN-ELEGANCE" },
    { dummyTag: "<!--[CATTA_SYNC:CELESTIAL_ROMANCE] -->", fileKey: "sol_37", promptId: "37_CELESTIAL-ROMANCE" },
    { dummyTag: "<!--[CATTA_SYNC:WUXIA_MARTIAL] -->", fileKey: "sol_38", promptId: "38_WuxiaMartial" },
    { dummyTag: "<!--[CATTA_SYNC:TEXT_COLOR_PALETTE] -->", fileKey: "sol_39", promptId: "39_PALETTE_GENERATOR" },
    { dummyTag: "<!--[CATTA_SYNC:CHOICE_GENERATOR] -->", fileKey: "sol_40", promptId: "40_CHOICE_GENERATION" },
    { dummyTag: "<!--[CATTA_SYNC:PREGNANCY_CHECK] -->", fileKey: "sol_41", promptId: "41_PREGNANCY_CHECK" },
    { dummyTag: "<!--[CATTA_SYNC:core_sys] -->", fileKey: "sol_00_1", promptId: "00_1_core_Sys" },
    { dummyTag: "<!--[CATTA_SYNC:core_navi] -->", fileKey: "navi_00", promptId: "00_core_navi" },
    { dummyTag: "<!--[CATTA_SYNC:catta1] -->", fileKey: "sol_42", promptId: "42_catta1" },
    { dummyTag: "<!--[CATTA_SYNC:catta2] -->", fileKey: "sol_43", promptId: "43_catta2" },
    { dummyTag: "<!--[CATTA_SYNC:catta3] -->", fileKey: "sol_44", promptId: "44_catta3" },
    { dummyTag: "<!--[CATTA_SYNC:catta4] -->", fileKey: "sol_45", promptId: "45_catta4" },
    { dummyTag: "<!--[CATTA_SYNC:catta5] -->", fileKey: "sol_46", promptId: "46_catta5" },
    { dummyTag: "<!--[CATTA_SYNC:catta6] -->", fileKey: "sol_47", promptId: "47_catta6" },
    { dummyTag: "<!--[CATTA_SYNC:catta7] -->", fileKey: "sol_48", promptId: "48_catta7" },
    { dummyTag: "<!--[CATTA_SYNC:catta8] -->", fileKey: "sol_49", promptId: "49_catta8" },
    { dummyTag: "<!--[CATTA_SYNC:catta9] -->", fileKey: "sol_50", promptId: "50_catta9" },
    { dummyTag: "<!--[CATTA_SYNC:catta10] -->", fileKey: "sol_51", promptId: "51_catta10" },
    { dummyTag: "<!--[CATTA_SYNC:catta11] -->", fileKey: "sol_52", promptId: "52_catta11" },
    { dummyTag: "<!--[CATTA_SYNC:catta12] -->", fileKey: "sol_53", promptId: "53_catta12" },
    { dummyTag: "<!--[CATTA_SYNC:catta13] -->", fileKey: "sol_54", promptId: "54_catta13" },
    { dummyTag: "<!--[CATTA_SYNC:catta14] -->", fileKey: "sol_55", promptId: "55_catta14" },
    { dummyTag: "<!--[CATTA_SYNC:catta15] -->", fileKey: "sol_56", promptId: "56_catta15" },
    { dummyTag: "<!--[CATTA_SYNC:catta16] -->", fileKey: "sol_57", promptId: "57_catta16" },
    { dummyTag: "<!--[CATTA_SYNC:catta17] -->", fileKey: "sol_58", promptId: "58_catta17" },
    { dummyTag: "<!--[CATTA_SYNC:catta18] -->", fileKey: "sol_59", promptId: "59_catta18" },
    { dummyTag: "<!--[CATTA_SYNC:catta19] -->", fileKey: "sol_60", promptId: "60_catta19" },
    { dummyTag: "<!--[CATTA_SYNC:catta20] -->", fileKey: "sol_61", promptId: "61_catta20" }

];

console.log("📦 Catta Addon DB: Loaded SOL_V12 Addons");